package com.astrology.report;

import com.astrology.core.Rashi;

public class GeneralPrediction {

    public static String getCharacterPrediction(Rashi lagna) {
        return switch (lagna) {
            case ARIES -> "You have started your life in a favorable environment. You possess excellent memory and rarely forget a favor. Generous to a fault, you are a very organized person, which reflects in your work, especially in your attire and residence. Personally attractive and elegant, you are broad-minded and remain thoughtful even in adverse situations. You are highly ambitious and set lofty goals for yourself.";
            case TAURUS -> "You are a very practical and steady individual. You believe in hard work and have a deep appreciation for beauty, art, and comfort. You possess a strong will and determination. Once you set your mind on a goal, you rarely back down. You are loyal and trustworthy, making you an excellent friend. However, your stubbornness can sometimes lead to conflicts.";
            case GEMINI -> "You are intellectually curious, versatile, and highly communicative. You possess a quick wit and love engaging in stimulating conversations. Adaptable to any situation, you thrive on variety and change. You have a youthful energy and are always eager to learn new things. Your dual nature means you can see both sides of any issue, though it may also make you appear inconsistent at times.";
            case CANCER -> "You are deeply intuitive, emotional, and highly imaginative. Family and home are paramount to your sense of security. You are fiercely protective of your loved ones and possess a nurturing spirit. Your sensitivity allows you to connect deeply with others, but it also means you are easily hurt. You have an excellent memory and hold onto the past dearly.";
            case LEO -> "You are a natural-born leader, exuding confidence, charisma, and magnanimity. You possess a strong desire to shine and be recognized for your talents. Generous and warm-hearted, you inspire those around you with your dramatic flair and enthusiasm. You are fiercely loyal to your friends and expect the same in return. Your pride is your greatest asset and your biggest vulnerability.";
            case VIRGO -> "You are meticulous, analytical, and highly observant. You possess a sharp intellect and a keen eye for detail. Always striving for perfection, you are a hard worker who takes immense pride in your practical accomplishments. You are deeply caring and love to serve others, though your critical nature can sometimes make you seem overly demanding of both yourself and those around you.";
            case LIBRA -> "You are charming, diplomatic, and highly focused on balance and harmony. You possess a natural grace and an innate sense of aesthetics and beauty. You excel in partnerships and always seek fair solutions to conflicts. Your sociability makes you extremely popular, but your desire to please everyone can sometimes lead to indecisiveness and a fear of confrontation.";
            case SCORPIO -> "You are intensely passionate, resourceful, and deeply mysterious. You possess a penetrating mind and an unyielding will. You are not afraid to delve into the darker aspects of life and are constantly seeking profound transformations. Fiercely loyal and protective, you make a powerful ally but a formidable enemy. Your emotional depth is matched only by your desire for control.";
            case SAGITTARIUS -> "You are adventurous, philosophical, and endlessly optimistic. You possess a restless spirit and a deep hunger for knowledge and truth. Always looking towards the horizon, you love exploring new cultures and ideas. You are honest and straightforward, sometimes to the point of bluntness. Your love for freedom is paramount, making you highly independent and enthusiastic.";
            case CAPRICORN -> "You are disciplined, ambitious, and incredibly pragmatic. You possess a strong sense of responsibility and a relentless drive to achieve your goals. You are the architect of the zodiac, capable of building lasting structures through patience and hard work. Though you may appear reserved or serious, you are deeply loyal to your family and friends and possess a dry, understated sense of humor.";
            case AQUARIUS -> "You are innovative, eccentric, and deeply humanitarian. You possess a brilliant, forward-thinking mind and are always looking for ways to improve society. You value your independence and often rebel against conventional norms. Though you are highly sociable and have a vast network of friends, you can sometimes appear emotionally detached or aloof in your pursuit of intellectual ideals.";
            case PISCES -> "You are compassionate, artistic, and deeply spiritual. You possess an empathetic soul and are highly sensitive to the emotions of those around you. Your imagination knows no bounds, making you incredibly creative and intuitive. You often seek to escape the harsh realities of the world through art, music, or spiritual practices. Your selfless nature makes you a devoted friend and partner.";
        };
    }

    public static String getHealthPrediction(Rashi lagna) {
        return switch (lagna) {
            case ARIES -> "Your health constitution is generally excellent, but you may suffer from nervous disorders and indigestion. The primary reason is your overly sensitive nature. You tend to exhaust your vital energy quickly. Overindulgence is the main cause of indigestion. To maintain good health, ensure you take time to rest and avoid eating heavy meals late at night.";
            case TAURUS -> "You generally enjoy robust health and a strong physical constitution. However, you may be prone to throat infections, thyroid issues, and weight gain due to a love for rich foods. Regular exercise and a balanced diet are essential to keep sluggishness at bay.";
            case GEMINI -> "Your active mind can sometimes lead to nervous exhaustion, anxiety, or respiratory issues. You are prone to respiratory infections and shoulder/arm pain. Taking time to practice deep breathing and mental relaxation is crucial for your overall well-being.";
            case CANCER -> "Your emotional state deeply affects your physical health. You may experience digestive issues, stomach ulcers, or chest-related problems when stressed. Emotional stability and a nurturing environment are the keys to maintaining your physical vitality.";
            case LEO -> "You possess strong vitality and a robust heart. However, you must guard against heart conditions, back pain, and spinal issues. Stress from overexertion and a desire to constantly lead can take a toll. Ensure you balance your active lifestyle with adequate cardiovascular care.";
            case VIRGO -> "You are highly health-conscious but your nervous system and digestive tract are sensitive. You are prone to allergies, indigestion, and hypochondria. A strict, clean diet and routine are necessary to keep your digestion functioning smoothly.";
            case LIBRA -> "Your health is generally good, but you are susceptible to kidney and lower back issues. You thrive on balance, and any physical or emotional extremes can disrupt your well-being. Drinking plenty of water and avoiding excess sugar is vital for your health.";
            case SCORPIO -> "You have incredible recuperative powers and can bounce back from severe illnesses. You are prone to issues related to the reproductive system and excretory organs. Maintaining emotional equilibrium and avoiding obsessive behaviors is key to your long-term health.";
            case SAGITTARIUS -> "Your active lifestyle keeps you fit, but you are prone to accidents, hip, and thigh injuries. Liver issues may arise from overindulgence in food or drink. Regular outdoor activities and a moderate diet will keep your robust energy levels intact.";
            case CAPRICORN -> "You tend to grow stronger and healthier as you age. You are prone to joint pain, arthritis, and skin conditions. Ensuring you get enough calcium and maintaining flexibility through exercise is critical to prevent stiffness in your bones and joints.";
            case AQUARIUS -> "Your nervous system is highly sensitive, and you may suffer from poor circulation or ankle/calf injuries. You need regular, gentle exercise to keep your blood flowing. Mental stimulation is good, but you must avoid burning out your nervous energy.";
            case PISCES -> "Your physical health is closely tied to your immune system and lymphatic functions. You are highly susceptible to foot problems, colds, and environmental toxins. A peaceful environment, adequate sleep, and avoiding harsh chemicals are necessary for your health.";
        };
    }

    public static String getCareerPrediction(Rashi lagna) {
        return switch (lagna) {
            case ARIES -> "You will excel in fields related to mass communication, leadership, and entrepreneurship. Your personality is exemplary and attractive, making you well-suited for roles that require constant imitation and public interaction. You thrive in environments that offer new challenges and a bit of risk.";
            case TAURUS -> "You are drawn to careers in finance, banking, agriculture, and the arts. Your steadfast nature makes you an excellent manager or administrator. You prefer stable, secure jobs where you can slowly build wealth and see tangible results from your hard work.";
            case GEMINI -> "Your excellent communication skills make you perfectly suited for journalism, sales, writing, and teaching. You need a fast-paced career that offers variety and mental stimulation. Routine jobs will quickly bore you, so look for roles that allow you to multitask.";
            case CANCER -> "You excel in nurturing and caregiving professions such as nursing, teaching, human resources, and real estate. Your empathetic nature allows you to connect deeply with clients or patients. You thrive in careers that offer emotional satisfaction and a sense of belonging.";
            case LEO -> "You are destined for leadership roles, management, politics, or the entertainment industry. You need a career that offers public recognition and allows you to shine. You are a natural boss who inspires subordinates with your vision and dramatic flair.";
            case VIRGO -> "You are perfect for roles in healthcare, accounting, editing, and scientific research. Your meticulous attention to detail and analytical skills make you an invaluable asset in any organization. You prefer to work behind the scenes to ensure everything runs flawlessly.";
            case LIBRA -> "You are well-suited for law, diplomacy, public relations, and the beauty/fashion industry. Your innate sense of fairness and aesthetic eye make you a great mediator or designer. You excel in partnerships and collaborative work environments.";
            case SCORPIO -> "Your penetrating mind is ideal for research, psychology, investigation, and surgery. You excel in careers that require deep focus and the unearthing of hidden truths. You thrive in high-pressure environments where transformation and crisis management are required.";
            case SAGITTARIUS -> "You are drawn to higher education, travel, philosophy, and law. You need a career that offers freedom, movement, and the opportunity to constantly learn. You make an excellent professor, explorer, or international business liaison.";
            case CAPRICORN -> "You are the quintessential executive, perfectly suited for corporate leadership, engineering, and government administration. You are highly ambitious and willing to climb the corporate ladder slowly and steadily to achieve lasting success and authority.";
            case AQUARIUS -> "You excel in technology, social work, science, and astrology. Your innovative mind allows you to see future trends before anyone else. You prefer working in unconventional environments or NGOs where you can contribute to the betterment of humanity.";
            case PISCES -> "You are naturally drawn to the arts, music, charity work, and healthcare. Your boundless imagination and deep empathy make you a gifted artist or healer. You function best in creative, unstructured environments where your intuition can guide your work.";
        };
    }

    public static String getFinancePrediction(Rashi lagna) {
        return switch (lagna) {
            case ARIES -> "The question of finance is highly specific for you. There is always a possibility of uncertainty and fluctuations in your wealth, but your innovative ideas will help you earn significantly. Avoid speculation and gambling. You will make money in unusual ways, perhaps as an inventor or an extraordinary businessman.";
            case TAURUS -> "You have a natural talent for accumulating wealth. You are careful with your spending and prefer secure, long-term investments over risky ventures. Financial security is deeply important to you, and you will steadily build a solid financial foundation throughout your life.";
            case GEMINI -> "Your financial situation may be variable, reflecting your dual nature. You have the cleverness to make money quickly through various streams, but you may also spend it just as fast on your many interests. Learning to budget and focus on long-term savings is crucial.";
            case CANCER -> "You are highly protective of your finances and prefer to save for a rainy day. You are excellent at managing household budgets and investing in real estate or secure bonds. Financial stability brings you emotional peace, so you rarely take unnecessary financial risks.";
            case LEO -> "You have a grand approach to money and love to spend on luxury, entertainment, and generosity towards others. You are capable of attracting significant wealth, but you must guard against extravagance. Your financial success is often tied to your career achievements and public status.";
            case VIRGO -> "You are meticulous and highly organized with your finances. You rarely overspend and are excellent at finding bargains and making prudent investments. Your analytical skills ensure that your financial portfolio is well-managed, leading to steady and secure growth.";
            case LIBRA -> "You enjoy the finer things in life and may spend heavily on art, fashion, and social events. You often attract wealth through partnerships, marriage, or collaborative business ventures. Maintaining a balanced budget can be challenging, but your charm often brings financial opportunities.";
            case SCORPIO -> "You are highly secretive and strategic about your finances. You possess a keen instinct for investments, inheritances, and managing other people's money. You have the ability to amass significant wealth, often through transformative or hidden ventures.";
            case SAGITTARIUS -> "You view money as a tool for freedom and experience rather than something to hoard. You are lucky in financial matters but can be overly optimistic or reckless with investments. Learning financial discipline will ensure your adventures are well-funded.";
            case CAPRICORN -> "You are extremely disciplined and strategic with your money. You view wealth as a measure of success and are willing to work tirelessly to achieve financial independence. You are an excellent long-term investor and rarely make impulsive financial decisions.";
            case AQUARIUS -> "Your approach to money is unconventional. You may experience sudden financial gains or losses due to your innovative but unpredictable nature. You are more interested in funding your ideals or technological pursuits than in accumulating traditional wealth.";
            case PISCES -> "You are not particularly materialistic and may struggle with the practicalities of money management. You are generous to a fault and may be taken advantage of financially. Relying on a trusted financial advisor or partner will help you maintain financial stability.";
        };
    }
}
