package com.astrology.report;

import com.astrology.core.Nakshatra;

public class NakshatraPrediction {

    public static String getNakshatraPrediction(Nakshatra nakshatra) {
        return switch (nakshatra) {
            case ASHWINI -> "You are highly energetic, dynamic, and full of youthful vitality. As the first Nakshatra, Ashwini natives love initiating new projects and possess a pioneering spirit. You are quick-witted, charming, and possess a natural healing touch. However, you may struggle with impatience and a tendency to leave projects unfinished.";
            case BHARANI -> "You are strong-willed, determined, and highly creative. Bharani natives are deeply passionate and possess a magnetic personality. You are not afraid to face the darker aspects of life and often undergo significant transformations. While you are deeply caring, your stubbornness and intense desires can sometimes lead to conflicts.";
            case KRITTIKA -> "You are ambitious, courageous, and fiercely independent. Represented by the blade, Krittika natives have a sharp intellect and a cutting sense of humor. You are highly protective of your loved ones and possess a strong sense of justice. Your fiery nature makes you a natural leader, but you must guard against arrogance.";
            case ROHINI -> "You are deeply sensual, artistic, and highly romantic. Rohini natives appreciate beauty, luxury, and comfort. You possess a calm and steady demeanor, making you a reliable friend and partner. You have a natural talent for agriculture or the arts. Your challenge lies in overcoming jealousy and possessiveness.";
            case MRIGASHIRA -> "You are curious, gentle, and highly inquisitive. Constantly searching for truth and meaning, Mrigashira natives love to travel and explore new ideas. You are an excellent communicator and possess a poetic soul. However, your restless mind can sometimes lead to anxiety and a lack of focus.";
            case ARDRA -> "You are intelligent, analytical, and deeply emotional. Ardra natives often experience intense emotional storms that ultimately lead to profound spiritual growth. You possess a sharp, investigative mind and excel in research or technology. Your challenge is learning to channel your intense emotions constructively.";
            case PUNARVASU -> "You are optimistic, philosophical, and deeply nurturing. Punarvasu natives possess a natural grace and a love for tradition and family. You are highly adaptable and always bounce back from adversity with a renewed sense of hope. You make an excellent teacher or counselor, guiding others with your wisdom.";
            case PUSHYA -> "You are deeply caring, spiritual, and highly disciplined. Pushya is considered one of the most auspicious Nakshatras. You possess a strong sense of duty and excel in caregiving professions. You are highly respected in your community for your ethical standards. Your challenge is learning to prioritize your own needs alongside others.";
            case ASHLESHA -> "You are mysterious, intuitive, and highly observant. Ashlesha natives possess a penetrating gaze and a deep understanding of human psychology. You are fiercely protective of your inner circle and possess a strong survival instinct. Your challenge lies in overcoming suspicion and learning to trust others fully.";
            case MAGHA -> "You are proud, traditional, and deeply connected to your ancestry. Magha natives possess a regal bearing and a strong desire for respect and authority. You are highly ambitious and often achieve significant success in your career. Your challenge is balancing your desire for power with humility and compassion.";
            case PURVA_PHALGUNI -> "You are charming, sociable, and deeply romantic. Purva Phalguni natives love the finer things in life and possess a natural flair for the dramatic. You excel in the arts, entertainment, or hospitality. You are deeply loyal in love, but you must guard against vanity and an over-reliance on physical appearances.";
            case UTTARA_PHALGUNI -> "You are responsible, practical, and highly independent. Uttara Phalguni natives possess a strong work ethic and are naturally inclined towards public service or leadership. You are a reliable and steadfast friend, always willing to lend a helping hand. Your challenge is learning to relax and enjoy the fruits of your labor.";
            case HASTA -> "You are meticulous, skilled, and highly analytical. Hasta natives possess incredible dexterity and excel in crafts, writing, or healing therapies. You have a sharp, humorous mind and love engaging in intellectual debates. Your challenge is overcoming nervous anxiety and a tendency to overthink every detail.";
            case CHITRA -> "You are charismatic, artistic, and deeply dynamic. Chitra natives possess a brilliant, shining personality and love to stand out from the crowd. You have a natural talent for design, architecture, or fashion. Your challenge is balancing your desire for perfection with the messy reality of human relationships.";
            case SWATI -> "You are diplomatic, adaptable, and highly focused on balance. Swati natives possess a gentle, airy nature and excel in communication and trade. You are highly independent and value your freedom above all else. Your challenge is overcoming indecisiveness and learning to stand firm in your convictions.";
            case VISHAKHA -> "You are ambitious, goal-oriented, and fiercely determined. Vishakha natives possess a strong, competitive spirit and are not afraid to work hard for what they want. You often achieve significant success later in life. Your challenge is managing your intense desires and avoiding ruthlessness in your pursuit of power.";
            case ANURADHA -> "You are devoted, spiritual, and highly compassionate. Anuradha natives possess a deep love for humanity and excel in roles that require teamwork and cooperation. You have a strong interest in the occult or hidden sciences. Your challenge is overcoming melancholy and learning to maintain healthy emotional boundaries.";
            case JYESHTHA -> "You are intense, authoritative, and deeply protective. Jyeshtha natives possess a commanding presence and are often seen as the eldest or most responsible in their family. You have a sharp, analytical mind and excel in investigative work. Your challenge is managing your pride and a tendency towards dominance.";
            case MOOLA -> "You are philosophical, investigative, and deeply transformative. Moola natives are driven to uncover the root cause of any issue. You often experience significant upheavals in life that lead to profound spiritual awakenings. Your challenge is learning to rebuild after destruction and embracing the chaotic nature of life.";
            case PURVA_ASHADHA -> "You are proud, invincible, and deeply optimistic. Purva Ashadha natives possess an unyielding spirit and are impossible to defeat. You have a strong sense of justice and love engaging in debates. Your challenge is overcoming a tendency towards confrontation and learning to compromise with others.";
            case UTTARA_ASHADHA -> "You are disciplined, highly ambitious, and deeply responsible. Uttara Ashadha natives possess a strong, enduring will and are destined for leadership. You are highly respected for your integrity and work ethic. Your challenge is learning to balance your demanding career with your personal and emotional needs.";
            case SHRAVANA -> "You are attentive, scholarly, and deeply compassionate. Shravana natives possess excellent listening skills and are naturally drawn to teaching, counseling, or linguistics. You are highly respected for your wisdom and gentle nature. Your challenge is overcoming a tendency towards isolation and melancholy.";
            case DHANISHTHA -> "You are musical, wealthy, and highly rhythmic. Dhanishtha natives possess a natural talent for the arts, particularly music and dance. You are highly ambitious and often achieve significant financial success. Your challenge is learning to share your wealth and overcoming a tendency towards emotional detachment.";
            case SHATABHISHA -> "You are eccentric, healing, and deeply humanitarian. Shatabhisha natives possess a unique, forward-thinking mind and excel in medicine, astrology, or technology. You are fiercely independent and often keep your true feelings hidden. Your challenge is learning to open up emotionally and trust others.";
            case PURVA_BHADRAPADA -> "You are passionate, mystical, and deeply transformative. Purva Bhadrapada natives possess a fiery, intense nature and are often drawn to the darker or more mysterious aspects of life. You have a strong, independent streak. Your challenge is managing your intense emotions and avoiding destructive behaviors.";
            case UTTARA_BHADRAPADA -> "You are peaceful, compassionate, and highly spiritual. Uttara Bhadrapada natives possess a deep, ocean-like wisdom and are naturally drawn to meditation or charity work. You are highly empathetic and make an excellent counselor or healer. Your challenge is overcoming laziness and a tendency to escape reality.";
            case REVATI -> "You are nurturing, wealthy, and deeply empathetic. Revati natives possess a gentle, loving soul and are deeply connected to animals and nature. You are highly intuitive and often possess psychic abilities. Your challenge is overcoming a tendency to take on others' burdens and learning to protect your own energy.";
        };
    }
}
