server:
  port: 8080
  
astrology:
  ephe-path: ./ephe
  default-ayanamsha: LAHIRI
  default-house-system: WHOLE_SIGN
  
spring:
  application:
    name: Vedic Astrology Engine
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
